#!/bin/bash
export JEKYLL_VERSION=latest
docker run --rm \
  --volume="$PWD:/srv/jekyll:Z" \
  --volume="$PWD/vendor/bundle:/usr/local/bundle:Z" \
  --publish 4000:4000 \
  -it jekyll/jekyll:$JEKYLL_VERSION \
  $*
